Line.create!([
  {name: "Blondme Lightener", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Igora-Vario Lightener", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Igora-expert-mousse", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Vibrance-gloss-and-tone", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Igora-vibrance", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Essensity", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Igora-Color10", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Igora-Royal ", unit: "oz", brand: Brand.find_by(name: "Schwarzkopf")},
  {name: "Lighten Up Lightener", unit: "oz", brand: Brand.find_by(name: "Paul Mitchell")},
  {name: "Dual-Purpose Lightener", unit: "oz", brand: Brand.find_by(name: "Paul Mitchell")},
  {name: "Synchro Lift Lightener", unit: "oz", brand: Brand.find_by(name: "Paul Mitchell")},
  {name: "PM Shine XG Demi Permanent", unit: "oz", brand: Brand.find_by(name: "Paul Mitchell")},
  {name: "Color XG Permanent", unit: "oz", brand: Brand.find_by(name: "Paul Mitchell")},
  {name: "Flash-lift Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "5/15 Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Up-to-7 Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blonde-dimensions Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blonde-glam Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blonde-icing Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Base-breakers Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blue-oil-lightening-system Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "High-lift-conditioning-cream Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blonde-idol  Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Blonde-Dimension Lightener", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Prismatic Permanent", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "EQ Cover Plus Brightenin", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "EQ Cream Equalising Con", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Demi Permanent Shades EQ Gloss", unit: "oz", brand: Brand.find_by(name: "Redken")},
  {name: "Permanent Color Fusion", unit: "oz", brand: Brand.find_by(name: "Redken")}
])
